### PR TITLE
Updated snowflake-sqlalchemy dependency

### PR DESCRIPTION
**Pull request by corford**
To resolve https://github.com/snowflakedb/snowflake-connector-python/pull/210

### CODE REVIEW

**Comment by sesprit** [comment]
Confirmed this fix to be working.

@hershaw can you give this one a look as well? Also what's needed to make a new version?

**Comment by hershaw** [comment]
That's it! We've got full CI/CD so we just need to merge this in and pypi will be updated. Am doing so now.

**Comment by corford** [comment]
@hershaw Can you merge when you get a moment? Snowflake-sqlalchemy version bump is needed so snowflake-connector-python package remains current (since it uses a lot of unpinned upstream dependencies that have a tendency to break and not all fixes for get backported).

**Comment by hershaw** [comment]
Also, sorry for missing the earlier request for the merge. Not sure how the notification got lost :-(

**Comment by corford** [comment]
Thanks Sam. Confidence level is good, should be fine.

**Pull request merged**
